site_name: Arisa | Blog
site_description: Arisa 的个人博客
site_author: Akiba Arisa
site_url: https://blog.arisa.moe/

repo_url: https://github.com/zhanbao2000/blog
repo_name: zhanbao2000/blog

theme:
  name: material
  custom_dir: overrides
  favicon: assets/favicon.ico
  icon:
    logo: octicons/code-review-16
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: 进入夜间模式
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: 进入日间模式
  language: 'zh'
  features:
    - navigation.tabs
    - navigation.top
    - navigation.tracking

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/zhanbao2000
      name: AkibaArisa on GitHub
    - icon: fontawesome/brands/steam
      link: https://steamcommunity.com/id/akibaarisa
      name: AkibaArisa on Steam

extra_css:
  - stylesheets/custom.css

plugins:
  - search
  - blogging:
      locale: zh_CN
      dirs:
        - blog
      features:
        tags: {}
      theme:
        name: card
        time_format: '%Y-%m-%d %H:%M:%S'
        meta_time_format: '%Y-%m-%d %H:%M:%S'
  - git-revision-date-localized:
      enable_creation_date: true
      type: iso_datetime

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

copyright: 'Copyright &copy; 2023 Akiba Arisa'
